// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Data;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    partial class TodoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TodoApp.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UseruId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UseruId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "For Birthday",
                            DueDate = new DateTime(2023, 3, 18, 11, 48, 24, 592, DateTimeKind.Local).AddTicks(1476),
                            Status = false,
                            Title = "Shopping"
                        },
                        new
                        {
                            Id = 2,
                            Description = "In Jump Training",
                            DueDate = new DateTime(2023, 3, 19, 11, 48, 24, 592, DateTimeKind.Local).AddTicks(1492),
                            Status = false,
                            Title = "Learn C#"
                        },
                        new
                        {
                            Id = 3,
                            Description = "For Jump Training",
                            DueDate = new DateTime(2023, 3, 19, 11, 48, 24, 592, DateTimeKind.Local).AddTicks(1493),
                            Status = false,
                            Title = "Learn MSSQL"
                        });
                });

            modelBuilder.Entity("TodoApp.Models.User", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uId"), 1L, 1);

                    b.Property<string>("uEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("uStatus")
                        .HasColumnType("bit");

                    b.HasKey("uId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TodoApp.Models.Todo", b =>
                {
                    b.HasOne("TodoApp.Models.User", null)
                        .WithMany("Todos")
                        .HasForeignKey("UseruId");
                });

            modelBuilder.Entity("TodoApp.Models.User", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
